### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-auth-local#8]
Suggest renaming this repo to `adapt-authoring-auth-local` for better future compatibility with other auth types - this naming convention also better follows the general left -> right grouping (i.e. `[PROJECT]-[PRODUCT]-[FEATURE]-[SUBFEATURE]`)

**Comment by taylortom** [comment]
@chris-steele given you're looking into auth stuff - do you think this is still useful?

**Comment by chris-steele** [comment]
yep looks sensible to me @taylortom

**Comment by taylortom** [comment]
Done
